// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_erd1iqm8G",
    "aws_user_pools_web_client_id": "4o60vj7qu0cisn6d9p20nscjo",
    "aws_content_delivery_bucket": "client-20181218140925-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://client-20181218140925-hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
